repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: check-ast

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py310-plus]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python # Should be a command that runs python3.6+
        args: [
            --target-version=py310
        ]
  - repo: https://github.com/hakancelikdev/unimport.git
    rev: 0.14.1
    hooks:
      - id: unimport
        entry: bash -c 'export LIBCST_PARSER_TYPE=native && unimport --exclude=__init__.py --remove --gitignore'
  - repo: local
    hooks:
    - id: pylint1
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: [
        --disable=all,
        --enable=undefined-variable,eval-used
      ]
  - repo: local
    hooks:
    - id: pylint2
      name: pylint
      entry: pylint
      language: system
      types: [python]
      exclude: ^apps/markets_robot
      args: [
        --disable=all,
        --enable=no-name-in-module,
      ]